services:
  - type: web
    name: hackathon-updates-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID 
        sync: false
      - key: PORT
        value: 8080
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
