name: Hackathon Bot

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Chrome for Selenium
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Run bot
      run: python main.py once
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        SCRAPE_INTERVAL_HOURS: ${{ secrets.SCRAPE_INTERVAL_HOURS || '6' }}
        TELEGRAM_RATE_LIMIT: ${{ secrets.TELEGRAM_RATE_LIMIT || '30' }}
        SCRAPING_DELAY: ${{ secrets.SCRAPING_DELAY || '2' }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL || 'INFO' }}
        ENVIRONMENT: 'production'
